name: Build and Push to ECR

on:
  push:
    branches: ["main"]

env:
  REPOSITORY: 205098647215.dkr.ecr.ap-southeast-1.amazonaws.com/inventium/web-agent
  IMAGE: web-agent
  VERSION: 0.0.1
  LOCATION: /home/runner/work/web-agent/web-agent

jobs:
  continuous-integration:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to AWS ECR
        run: |-
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 205098647215.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Build
        run: |-
          docker build --tag "$REPOSITORY:$VERSION" . --build-arg SERVICE_NAME=$IMAGE --build-arg FOLDER=$LOCATION

      - name: Publish
        run: |-
          docker push "$REPOSITORY:$VERSION"
